### ISSUE TITLE
Document new models HVDC

### ISSUE THREAD

**Issue by kennedy-mindermann** [Sienna-Platform/PowerOperationsModels.jl#50]
Document the new models that were created for 2T - HVDC: 

- [x] PWL losses model
- [x] VSC physical model (#1197)  
- [ ] Physical LCC model (https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1212)
- [x] Quadratic losses model (#1200)
